export const TRACKS = [
  { id: 'kick',  lbl: 'KICK',  col: '#FF4444', s: 'KCK' },
  { id: 'snare', lbl: 'SNARE', col: '#8B7355', s: 'SNR' },
  { id: 'hihat', lbl: 'HIHAT', col: '#B8A080', s: 'HHT' },
  { id: 'clap',  lbl: 'CLAP',  col: '#7D6548', s: 'CLP' },
  { id: 'bass',  lbl: 'BASS',  col: '#00DD77', s: 'BAS' },
  { id: 'lead',  lbl: 'LEAD',  col: '#00FF88', s: 'LED' },
  { id: 'stab',  lbl: 'STAB',  col: '#00CC66', s: 'STB' },
  { id: 'noise', lbl: 'NOISE', col: '#6B5040', s: 'NZZ' },
];

export const TRACK_KEYS = ['kick', 'snare', 'hihat', 'clap', 'bass', 'lead', 'stab', 'noise'];

export const SOUND_PRESETS = [
  { n: 'BERG',   v: [200, 10, .35, 2500, 0, 72] },
  { n: 'VAULT',  v: [80, 5, .50, 800, 0, 78] },
  { n: 'THROB',  v: [160, 15, .45, 1800, 0, 70] },
  { n: 'SMOKE',  v: [300, 25, .60, 1200, 0, 60] },
  { n: 'WIRE',   v: [600, 8, .08, 4000, 0, 68] },
  { n: 'LOOP',   v: [280, 20, .25, 3000, 0, 72] },
  { n: 'DUSK',   v: [180, 30, 1.4, 2000, 0, 50] },
  { n: 'IRON',   v: [350, 45, .12, 5000, 0, 65] },
  { n: 'PULSE',  v: [220, 0, .20, 3500, 0, 75] },
  { n: 'SLAB',   v: [100, 15, .70, 1500, 0, 70] },
  { n: 'VOID',   v: [60, 10, 1.0, 600, 0, 45] },
  { n: 'CHAIN',  v: [500, 55, .18, 6000, 0, 58] },
  { n: 'DUB',    v: [240, 60, .80, 2500, 0, 55] },
  { n: 'FOG',    v: [150, 20, 1.6, 900, 0, 48] },
  { n: 'STARK',  v: [440, 0, .15, 4500, 0, 70] },
  { n: 'CRUSH',  v: [130, 70, .30, 3500, 0, 80] },
];

export const KNOB_DEFS = [
  { id: 'hits',   lbl: 'HITS',   min: 0, max: 16,    val: 0,    col: '#FF4444', fmt: v => Math.round(v) },
  { id: 'rotate', lbl: 'ROTATE', min: 0, max: 15,    val: 0,    col: '#B8A080', fmt: v => Math.round(v) },
  { id: 'track',  lbl: 'TRACK',  min: 0, max: 7,     val: 0,    col: '#B8A080', fmt: v => TRACKS[Math.round(v)].s },
  { id: 'tempo',  lbl: 'TEMPO',  min: 40, max: 300,   val: 120,  col: '#00FF88', fmt: v => Math.round(v) },
  { id: 'pitch',  lbl: 'PITCH',  min: 20, max: 2000,  val: 440,  col: '#00DD77' },
  { id: 'decay',  lbl: 'DECAY',  min: .01, max: 2,    val: .3,   col: '#6B5040' },
  { id: 'filter', lbl: 'FILTER', min: 100, max: 12000, val: 5000, col: '#8B7355' },
  { id: 'glitch', lbl: 'GLITCH', min: 0, max: 100,    val: 20,   col: '#FF4444' },
  { id: 'volume', lbl: 'VOL',    min: 0, max: 100,    val: 70,   col: '#00DD77' },
];

const _ = 0, X = 1;
export const TRACK_PATTERNS = {
  kick: [
    { n: '4/4',       p: [X,_,_,_,X,_,_,_,X,_,_,_,X,_,_,_] },
    { n: 'BOOM BAP',  p: [X,_,_,_,_,_,_,_,X,_,X,_,_,_,_,_] },
    { n: 'BROKEN',    p: [X,_,_,_,_,_,X,_,_,_,X,_,_,_,_,_] },
    { n: 'SYNCO',     p: [X,_,_,X,_,_,X,_,_,_,X,_,_,_,X,_] },
    { n: 'MINIMAL',   p: [X,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_] },
    { n: 'DOUBLE',    p: [X,_,X,_,_,_,_,_,X,_,X,_,_,_,_,_] },
    { n: 'OFF BEAT',  p: [_,_,_,_,X,_,_,_,_,_,_,_,X,_,_,_] },
    { n: 'DOTTED',    p: [X,_,_,_,_,_,X,_,_,_,_,_,X,_,_,_] },
    { n: 'SCATTER',   p: [X,_,_,X,_,_,_,_,X,_,_,_,_,X,_,_] },
    { n: 'STOMP',     p: [X,_,X,_,X,_,_,_,X,_,X,_,X,_,_,_] },
    { n: 'HALFTIME',  p: [X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
    { n: 'ROLLING',   p: [X,_,_,X,_,_,X,_,_,X,_,_,X,_,_,_] },
    { n: 'PUNCHY',    p: [X,_,_,_,X,_,_,X,_,_,X,_,_,_,X,_] },
    { n: 'SPARSE',    p: [X,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_] },
    { n: 'TRESILLO',  p: [X,_,_,X,_,_,X,_,_,_,X,_,X,_,_,_] },
    { n: 'EMPTY',     p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
  ],
  snare: [
    { n: 'BACKBEAT',  p: [_,_,_,_,X,_,_,_,_,_,_,_,X,_,_,_] },
    { n: 'SKIP',      p: [_,_,_,_,X,_,_,_,_,_,_,_,_,X,_,_] },
    { n: 'GHOST',     p: [_,_,X,_,X,_,_,X,_,_,X,_,X,_,_,_] },
    { n: 'ROLL',      p: [_,_,_,_,X,_,_,_,_,_,_,_,X,X,X,X] },
    { n: 'ONE DROP',  p: [_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_] },
    { n: 'CROSS',     p: [_,_,_,X,_,_,_,_,_,_,_,X,_,_,_,_] },
    { n: 'DOUBLE',    p: [_,_,_,_,X,X,_,_,_,_,_,_,X,X,_,_] },
    { n: 'OFFBEAT',   p: [_,_,X,_,_,_,X,_,_,_,X,_,_,_,X,_] },
    { n: 'TRAP',      p: [_,_,_,_,X,_,_,_,_,_,_,_,X,_,_,X] },
    { n: 'HALFTIME',  p: [_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_] },
    { n: 'FILL',      p: [_,_,_,_,X,_,X,_,_,_,X,_,X,X,X,X] },
    { n: 'SHUFFLE',   p: [_,_,_,_,X,_,_,X,_,_,_,_,X,_,_,X] },
    { n: 'BLAST',     p: [X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X] },
    { n: 'FLAM',      p: [_,_,_,_,_,X,_,_,_,_,_,_,_,X,_,_] },
    { n: 'MARCH',     p: [X,_,_,_,X,_,_,_,X,_,_,_,X,_,_,_] },
    { n: 'EMPTY',     p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
  ],
  hihat: [
    { n: '8THS',      p: [X,_,X,_,X,_,X,_,X,_,X,_,X,_,X,_] },
    { n: '16THS',     p: [X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X] },
    { n: 'OFFBEAT',   p: [_,_,X,_,_,_,X,_,_,_,X,_,_,_,X,_] },
    { n: 'SHUFFLE',   p: [X,_,_,X,_,_,X,_,_,X,_,_,X,_,_,X] },
    { n: 'TRAP',      p: [X,X,_,X,X,X,_,X,X,X,_,X,X,X,X,X] },
    { n: 'BROKEN',    p: [X,_,X,X,_,_,X,_,X,_,X,X,_,_,X,_] },
    { n: 'SPARSE',    p: [X,_,_,_,X,_,_,_,X,_,_,_,X,_,_,_] },
    { n: 'GALLOP',    p: [X,X,_,_,X,X,_,_,X,X,_,_,X,X,_,_] },
    { n: 'TRIPLET',   p: [X,_,_,X,_,_,X,_,_,X,_,_,X,_,_,_] },
    { n: 'AFRO',      p: [X,X,_,X,X,_,X,X,_,X,X,_,X,X,_,X] },
    { n: 'CLAVE',     p: [X,_,_,X,_,_,X,_,_,_,X,_,X,_,_,_] },
    { n: 'SWING',     p: [X,_,_,X,_,X,_,_,X,_,_,X,_,X,_,_] },
    { n: 'SKIP',      p: [X,_,X,_,X,_,_,_,X,_,X,_,X,_,_,_] },
    { n: 'OPEN/CL',   p: [X,_,X,_,_,_,X,X,X,_,X,_,_,_,X,X] },
    { n: 'MINIMAL',   p: [_,_,X,_,_,_,X,_,_,_,X,_,_,_,X,_] },
    { n: 'EMPTY',     p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
  ],
  clap: [
    { n: 'BACKBEAT',  p: [_,_,_,_,X,_,_,_,_,_,_,_,X,_,_,_] },
    { n: 'DEMBOW',    p: [_,_,_,X,_,_,_,X,_,_,_,X,_,_,_,X] },
    { n: 'ACCENT',    p: [_,_,_,_,X,_,_,X,_,_,_,_,X,_,_,_] },
    { n: 'SPARSE',    p: [_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_] },
    { n: 'DOUBLE',    p: [_,_,_,_,X,X,_,_,_,_,_,_,X,X,_,_] },
    { n: 'BUILDUP',   p: [_,_,_,_,_,_,_,_,X,_,X,_,X,X,X,X] },
    { n: 'REGGAE',    p: [_,_,_,_,_,_,X,_,_,_,_,_,_,_,X,_] },
    { n: 'TRIPLET',   p: [_,_,_,X,_,_,X,_,_,X,_,_,_,_,_,_] },
    { n: 'OFF',       p: [_,X,_,_,_,X,_,_,_,X,_,_,_,X,_,_] },
    { n: 'FILL',      p: [_,_,_,_,_,_,_,_,X,X,X,X,X,X,X,X] },
    { n: 'PUSH',      p: [_,_,_,X,_,_,_,_,_,_,_,X,_,_,_,_] },
    { n: 'FUNK',      p: [_,_,_,_,X,_,_,_,_,_,_,X,X,_,_,_] },
    { n: '8THS',      p: [_,_,X,_,_,_,X,_,_,_,X,_,_,_,X,_] },
    { n: 'STOMP',     p: [X,_,_,_,X,_,_,_,X,_,_,_,X,_,_,_] },
    { n: 'RANDOM',    p: [_,X,_,_,_,_,X,_,_,_,_,X,_,_,X,_] },
    { n: 'EMPTY',     p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
  ],
  bass: [
    { n: 'ROOT',      p: [X,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_] },
    { n: 'OCTAVE',    p: [X,_,_,_,_,_,_,X,_,_,X,_,_,_,_,_] },
    { n: 'WALKING',   p: [X,_,_,_,X,_,_,_,X,_,_,_,X,_,_,_] },
    { n: 'SYNCO',     p: [X,_,_,X,_,_,X,_,_,_,X,_,_,X,_,_] },
    { n: 'OFFBEAT',   p: [_,_,X,_,_,_,X,_,_,_,X,_,_,_,X,_] },
    { n: 'DISCO',     p: [X,_,_,_,_,_,X,_,X,_,_,_,_,_,X,_] },
    { n: 'DUB',       p: [X,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_] },
    { n: 'GALLOP',    p: [X,_,X,_,_,_,_,_,X,_,X,_,_,_,_,_] },
    { n: 'FUNK',      p: [X,_,_,X,_,_,X,_,_,_,X,_,_,_,_,X] },
    { n: 'PUMPING',   p: [X,_,_,_,X,_,_,_,X,_,_,_,X,_,_,_] },
    { n: '16TH',      p: [X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X] },
    { n: 'ACID',      p: [X,_,_,X,_,X,_,_,X,_,_,X,_,X,_,_] },
    { n: 'SPARSE',    p: [X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
    { n: 'GROOVE',    p: [X,_,_,_,_,_,_,X,_,_,_,X,_,_,_,_] },
    { n: 'BOUNCE',    p: [X,_,_,_,_,X,_,_,X,_,_,_,_,X,_,_] },
    { n: 'EMPTY',     p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
  ],
  lead: [
    { n: 'MELODY1',   p: [X,_,_,_,_,_,X,_,_,_,X,_,_,_,_,_] },
    { n: 'STACCATO',  p: [X,_,X,_,X,_,X,_,X,_,X,_,X,_,X,_] },
    { n: 'ARPEGGIO',  p: [X,_,_,X,_,_,X,_,_,X,_,_,X,_,_,_] },
    { n: 'CALL',      p: [X,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_] },
    { n: 'RESPONSE',  p: [_,_,_,_,_,_,_,_,X,_,_,_,X,_,_,_] },
    { n: 'TRILL',     p: [X,X,_,_,X,X,_,_,X,X,_,_,X,X,_,_] },
    { n: 'RIFF',      p: [X,_,_,X,_,X,_,_,X,_,_,X,_,X,_,_] },
    { n: 'PULSE',     p: [X,_,_,_,X,_,_,_,X,_,_,_,X,_,_,_] },
    { n: 'SYNCO',     p: [_,_,X,_,_,X,_,_,_,_,X,_,_,X,_,_] },
    { n: 'LONG',      p: [X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
    { n: 'BUILDUP',   p: [_,_,_,_,_,_,_,_,X,_,X,_,X,X,X,X] },
    { n: 'CASCADE',   p: [X,_,_,_,_,X,_,_,_,_,X,_,_,_,_,X] },
    { n: 'DOTTED',    p: [X,_,_,X,_,_,_,X,_,_,X,_,_,_,X,_] },
    { n: 'CHORDS',    p: [X,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_] },
    { n: 'RANDOM',    p: [_,X,_,_,X,_,_,_,_,_,X,_,_,X,_,_] },
    { n: 'EMPTY',     p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
  ],
  stab: [
    { n: 'HITS',      p: [X,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_] },
    { n: 'CHOP',      p: [X,_,X,_,_,_,_,_,X,_,X,_,_,_,_,_] },
    { n: 'REGGAE',    p: [_,_,_,_,_,_,X,_,_,_,_,_,_,_,X,_] },
    { n: 'FUNK',      p: [_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,X] },
    { n: 'ACCENT',    p: [X,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_] },
    { n: 'ECHO',      p: [X,_,_,_,_,_,X,_,_,_,_,_,X,_,_,_] },
    { n: 'PULSE',     p: [X,_,_,_,X,_,_,_,X,_,_,_,X,_,_,_] },
    { n: 'SCATTER',   p: [_,X,_,_,_,_,X,_,_,_,X,_,_,_,_,_] },
    { n: 'HORNS',     p: [X,_,_,X,_,_,_,_,X,_,_,X,_,_,_,_] },
    { n: 'DUB',       p: [X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
    { n: 'FAST',      p: [X,X,_,_,X,X,_,_,X,X,_,_,X,X,_,_] },
    { n: 'SYNCO',     p: [_,_,X,_,_,_,_,X,_,_,X,_,_,_,_,X] },
    { n: 'DISCO',     p: [_,_,X,_,_,_,X,_,_,_,X,_,_,_,X,_] },
    { n: 'MINIMAL',   p: [_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_] },
    { n: 'FILL',      p: [_,_,_,_,_,_,_,_,_,_,_,_,X,X,X,X] },
    { n: 'EMPTY',     p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
  ],
  noise: [
    { n: 'FILLS',     p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X] },
    { n: 'RISERS',    p: [_,_,_,_,_,_,_,_,_,_,_,_,X,X,X,X] },
    { n: 'TEXTURE',   p: [X,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_] },
    { n: 'SCATTER',   p: [_,X,_,_,_,X,_,_,_,X,_,_,_,X,_,_] },
    { n: 'GLITCH',    p: [X,_,X,_,_,X,_,X,_,_,X,_,X,_,_,X] },
    { n: 'SPARSE',    p: [_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_] },
    { n: 'SWEEP',     p: [X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
    { n: 'BURST',     p: [_,_,_,_,_,_,_,_,X,X,X,X,_,_,_,_] },
    { n: 'PULSE',     p: [X,_,_,_,X,_,_,_,X,_,_,_,X,_,_,_] },
    { n: 'RAIN',      p: [_,X,_,X,_,X,_,X,_,X,_,X,_,X,_,X] },
    { n: 'BREATH',    p: [X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X] },
    { n: 'CHAOS',     p: [X,X,X,_,X,_,X,X,_,X,X,_,X,_,X,_] },
    { n: 'CRACKLE',   p: [_,_,X,_,_,_,_,_,_,_,X,_,_,_,_,_] },
    { n: 'STORM',     p: [X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X] },
    { n: 'DROP',      p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_] },
    { n: 'EMPTY',     p: [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_] },
  ],
};

export const MODE_NAMES = ['DRAW', 'PLAY', 'SOUND', 'BEATS'];
export const MODE_DESCS = [
  'Pads toggle steps for selected track',
  'Pads trigger instruments live',
  'Pads load sound presets',
  'Pads load pattern for selected track',
];

export const LEARN_BORDER = 'border-c1 animate-[learn-pulse_1s_infinite]';

export const KEY_MAP = {};
'1234qwerasdfzxcv'.split('').forEach((k, i) => { KEY_MAP[k] = i; });
